---
deployment:
  tasks:
    - export DEPLOYPATH=/home4/bharabgn/apps.bharani.tech/
    # - /bin/rm -Rf $DEPLOYPATH
    # - /bin/mkdir $DEPLOYPATH
    - /bin/cp build/* -r $DEPLOYPATH
    - /bin/cp ./.htaccess $DEPLOYPATH
    - /bin/cp ./services -r $DEPLOYPATH
