const BANK_HOLD = "BANK_HOLD";
const REC_TRX = "REC_TRX";
const TOP_BANKINGS = "TOP_BANKINGS";
const TOP_CREDIT_CARDS = "TOP_CREDIT_CARDS";

export { BANK_HOLD, REC_TRX, TOP_BANKINGS, TOP_CREDIT_CARDS };
