name: Deployment
on:
  push:
    branches:
      - develop
      - master
      - staging
  pull_request:
    branches:
      - develop
      - master
      - staging
  workflow_dispatch:

env:
  NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  # environment:
  #   name: Select Environment
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Select deployment environment
  #       run: |
  #         echo "Running on branch ${{ env.NAME }}"
  #         echo "lala = ${{ secrets.LALA }}"

  build:
    name: React Node.JS Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Select deployment environment
        run: |
          echo "Running on branch ${{ env.NAME }}"
          echo "var = ${{ vars.PRODUCTION_APP_ENV }}"
          echo "secret = ${{ secrets.DEV_HOST_PASSSWORD }}"

  #     - name: Use Node.js ${{ matrix.node-version }}
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #         cache: npm

  #     - name: clean cache
  #       run: npm cache clean --force
  #     - name: npm install
  #       run: npm install
  #     - name: Run build
  #       run: |
  #         npm run build
