name: Deployment
on:
  push:
    branches:
      - develop
      - master
      - staging
  pull_request:
    branches:
      - develop
      - master
      - staging
  workflow_dispatch:

jobs:
  Build:
    name: React Node.JS Build
    strategy:
      matrix:
        node-version: [20.x]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: clean cache
        run: npm cache clean --force
      - name: npm install
        run: npm install
      - name: npm run build
        run: npm run build

  DeployToDev:
    name: Deploy to DEV
    if: github.event.ref == 'refs/heads/develop'
    needs: [Build]
    runs-on: ubuntu-latest
    environment:
      name: develop
      url: https://dev.ledgerely.com
    steps:
      - name: Deploy
        run: echo "${{vars.APP_ENV}}"

  DeployToStaging:
    name: Deploy to STAGE
    if: github.event.ref == 'refs/heads/staging'
    needs: [Build]
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://stage.ledgerely.com
    steps:
      - name: Deploy
        run: echo "${{vars.APP_ENV}}"
