name: Deployment
on:
  push:
    branches:
      - develop
      - master
      - staging
  pull_request:
    branches:
      - develop
      - master
      - staging
  workflow_dispatch:

jobs:
  Build:
    name: React Node.JS Build
    strategy:
      matrix:
        node-version: [20.x]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
        env:
          CI: false

      - name: clean cache
        run: npm cache clean --force
      - name: npm install
        run: npm install
      - name: npm run build
        run: npm run build

  Deployment:
    name: Deploy to ${{github.ref_name}}
    if: github.event.ref == 'refs/heads/${{github.ref_name}}'
    needs: [Build]
    runs-on: ubuntu-latest
    environment:
      name: develop
    steps:
      - name: Starting Deployment
        run: echo "${{vars.APP_ENV}}"

      - name: Create .env file
        run: |
          echo "APP_ENV=${{ vars.APP_ENV }}" >> .env
          echo "BASE_URL=${{ vars.BASE_URL }}" >> .env
          echo "HOST_NAME=${{ secrets.HOST_NAME }}" >> .env
          echo "HOST_USERNAME=${{ secrets.HOST_USERNAME }}" >> .env
          echo "HOST_PASSSWORD=${{ secrets.HOST_PASSSWORD }}" >> .env
          echo "HOST_DATABASE=${{ secrets.HOST_DATABASE }}" >> .env
          echo "MAIL_PROTOCOL=${{ vars.MAIL_PROTOCOL }}" >> .env
          echo "MAIL_SMTP_HOST=${{ vars.MAIL_SMTP_HOST }}" >> .env
          echo "MAIL_SMTP_USER=${{ vars.MAIL_SMTP_USER }}" >> .env
          echo "MAIL_SMTP_PASSWORD=${{ vars.MAIL_SMTP_PASSWORD }}" >> .env
          echo "MAIL_TYPE=${{ vars.MAIL_TYPE }}" >> .env
          echo "MAIL_CHARSET=${{ vars.MAIL_CHARSET }}" >> .env
          echo "RAZORPAY_TEST_KEY_ID=${{ secrets.RAZORPAY_TEST_KEY_ID }}" >> .env
          echo "RAZORPAY_TEST_KEY_SECRET=${{ secrets.RAZORPAY_TEST_KEY_SECRET }}" >> .env
          echo "RAZORPAY_WEBHOOK_SECRET=${{ secrets.RAZORPAY_WEBHOOK_SECRET }}" >> .env
          echo "RAZORPAY_LIVE_KEY_ID=${{ secrets.RAZORPAY_LIVE_KEY_ID }}" >> .env
          echo "RAZORPAY_LIVE_KEY_SECRET=${{ secrets.RAZORPAY_LIVE_KEY_SECRET }}" >> .env

          cat .env

          tar -czf build.tar.gz /build
          tar -czf services.tar.gz /services

          curl -T "build.tar.gz" "ftp://${{ secrets.HOST_NAME}}/${{ vars.FTP_UPLOAD_DIR }}/" \
          curl -T "services.tar.gz" "ftp://${{ secrets.HOST_NAME}}/${{ vars.FTP_UPLOAD_DIR }}/" \
          --user "${{secrets.FTP_USER}}:${{ secrets.FTP_PASSWORD }}" \
          --ftp-create-dirs
