name: Deployment
on:
  push:
    branches:
      - develop
      - master
      - staging
  pull_request:
    branches:
      - develop
      - master
      - staging
  workflow_dispatch:

jobs:
  Build:
    name: React Node.JS Build
    strategy:
      matrix:
        node-version: [20.x]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: clean cache
        run: npm cache clean --force
      - name: npm install
        run: npm install
      - name: npm run build
        run: npm run build

  Deployment:
    name: Deploy to ${{github.ref_name}}
    if: github.event.ref == 'refs/heads/${{github.ref_name}}'
    needs: [Build]
    runs-on: ubuntu-latest
    environment:
      name: ${{ vars.RESERVED_ENV_NAME }}
    steps:
      - name: Starting Deployment
        run: echo "${{vars.APP_ENV}}"

      - name: Create .env file
        run: |
          echo "APP_ENV=${{ vars.APP_ENV }}" >> abc.txt
          echo "BASE_URL=${{ vars.BASE_URL }}" >> abc.txt
          echo "HOST_NAME=${{ secrets.HOST_NAME }}" >> abc.txt
          echo "HOST_USERNAME=${{ secrets.HOST_USERNAME }}" >> abc.txt
          echo "HOST_PASSSWORD=${{ secrets.HOST_PASSSWORD }}" >> abc.txt
          echo "HOST_DATABASE=${{ secrets.HOST_DATABASE }}" >> abc.txt
          echo "MAIL_PROTOCOL=${{ vars.MAIL_PROTOCOL }}" >> abc.txt
          echo "MAIL_SMTP_HOST=${{ vars.MAIL_SMTP_HOST }}" >> abc.txt
          echo "MAIL_SMTP_USER=${{ vars.MAIL_SMTP_USER }}" >> abc.txt
          echo "MAIL_SMTP_PASSWORD=${{ vars.MAIL_SMTP_PASSWORD }}" >> abc.txt
          echo "MAIL_TYPE=${{ vars.MAIL_TYPE }}" >> abc.txt
          echo "MAIL_CHARSET=${{ vars.MAIL_CHARSET }}" >> abc.txt
          echo "RAZORPAY_TEST_KEY_ID=${{ secrets.RAZORPAY_TEST_KEY_ID }}" >> abc.txt
          echo "RAZORPAY_TEST_KEY_SECRET=${{ secrets.RAZORPAY_TEST_KEY_SECRET }}" >> abc.txt
          echo "RAZORPAY_WEBHOOK_SECRET=${{ secrets.RAZORPAY_WEBHOOK_SECRET }}" >> abc.txt
          echo "RAZORPAY_LIVE_KEY_ID=${{ secrets.RAZORPAY_LIVE_KEY_ID }}" >> abc.txt
          echo "RAZORPAY_LIVE_KEY_SECRET=${{ secrets.RAZORPAY_LIVE_KEY_SECRET }}" >> abc.txt

          cat abc.txt

          curl -T "abc.txt" "ftp://${{ secrets.HOST_NAME}}/${{ vars.FTP_UPLOAD_DIR }}/" \
          --user "${{secrets.FTP_USER}}:${{ secrets.FTP_PASSWORD }}" \
          --ftp-create-dirs
