name: Deploy on push
on:
  push:
    branches:
      - develop
      - master
      - staging
  pull_request:
    branches:
      - develop
      - master
      - staging
  workflow_dispatch:

env:
  NAME: ${{ github.head_ref || github.ref_name }}
  FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
  APP_ENV: ${{ vars.APP_ENV }}

jobs:
  environment:
    name: Select Environment
    runs-on: ubuntu-latest
    steps:
      - name: Select deployment environment
        run: |
          echo "Running on branch ${{ env.NAME }}"
          echo "password ${{ env.FTP_PASSWORD }}"
          echo "appEnv ${{ env.APP_ENV }}"

  # build:
  #   name: React Node.JS Build
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       node-version: [20.x]

  #   steps:
  #     - name: Checkout the code
  #       uses: actions/checkout@v4

  #     - name: Use Node.js ${{ matrix.node-version }}
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #         cache: npm

  #     - name: clean cache
  #       run: npm cache clean --force
  #     - name: npm install
  #       run: npm install
  #     - name: Run build
  #       run: |
  #         npm run build
