name: 🚀 Deploy to Develop on push
on:
  push:
    branches:
      - develop
      - master
      - staging
  pull_request:
    branches:
      - develop
      - master
      - staging
  workflow_dispatch:

jobs:
  build:
    name: React Node.JS Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    env:
      REPOSITORY: ${{ github.repository }}
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
      APP_ENV: ${{ vars.APP_ENV }}
      BASE_URL: ${{ vars.BASE_URL }}
      MAIL_PROTOCOL: ${{ vars.MAIL_PROTOCOL }}
      MAIL_SMTP_HOST: ${{ vars.MAIL_SMTP_HOST }}
      MAIL_SMTP_USER: ${{ vars.MAIL_SMTP_USER }}
      MAIL_SMTP_PASSWORD: ${{ vars.MAIL_SMTP_PASSWORD }}
      MAIL_TYPE: ${{ vars.MAIL_TYPE }}
      MAIL_CHARSET: ${{ vars.MAIL_CHARSET }}
    steps:
      - name: Setting environment
        run: |
          echo $BASE_URL

      # - name: Checkout the code
      #   uses: actions/checkout@v4

      # - name: Use Node.js ${{ matrix.node-version }}
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: ${{ matrix.node-version }}
      #     cache: npm

      # - name: clean cache
      #   run: npm cache clean --force
      # - name: npm install
      #   run: npm install
      # - name: Run build
      #   run: |
      #     npm run build
