name: 🚀 Deploy to Develop on push
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  workflow_dispatch:

jobs:
  BUILD_UI_CODE_FOR_PR:
    name: Build the code for PR
    runs-on: ubuntu-latest
    container: node:18
    steps:
      - run: node --version
      - run: npm --version
      
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install node modules
        run: npm install

      - name: Build the artifact
        run: npm run build

      # - name: 📂 Sync front end files
      #   uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      #   with:
      #     server: "43.225.55.129"
      #     username: "bharabgn"
      #     password: "Bniwin@!123"
      #     port: "21"
      #     local-dir: build/
      #     server-dir: test/
