name: 🚀 Deploy to Develop on push
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  workflow_dispatch:

jobs:
  BUILD_UI_CODE_FOR_PR:
    name: Build the code for PR
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: clean cache
        run: npm cache clean --force
      - name: npm install
        run: npm install
      - name: Run build
        run: |
          npm run build
