name: 🚀 Deploy to Develop on push
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  workflow_dispatch:

jobs:
  create-envfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Hello develop branch
        run: echo "Hello develop branch"
        shell: bash
