name: 🚀 Deploy to Develop on push
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  workflow_dispatch:

jobs:
  BUILD_UI_CODE_FOR_PR:
    name: Build the code for PR
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20.x]
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: remove node_modules
        run: rm -rf node_modules/
      - name: Install deps
        run: |
          npm install
      - name: Run build
        run: |
          npm run build
