name: 🚀 Deploy to Staging on push
on:
  push:
    branches:
      - testing
  pull_request:
    branches:
      - testing
  workflow_dispatch:

jobs:
  create-envfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Hello staging branch
        run: echo "Hello staging branch"
        shell: bash
